name: Example Action

on:
  issues:
  issue_comment:
    types: [created, edited]
  pull_request:
  pull_request_review_comment:
    types: [created, edited]

jobs:
  comment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Comment
        id: awake-yet-action-js
        uses: shundor/awake-yet-action-js@main
